package app.recipio.local;
import static org.junit.Assert.*;
import android.content.Context;
import android.graphics.*;
import android.media.ExifInterface;
import android.net.Uri;
import android.system.Os;
import androidx.test.platform.app.InstrumentationRegistry;
import java.io.*;
import java.util.*;
import org.junit.*;

/** Generated fixtures only. Actual Android Bitmap/EXIF/file primitives; zero network. */
public class AiTemporaryImagesInstrumentedTest {
    private Context context;private File cache;private AiTemporaryImages images;private UUID operation;
    @Before public void setup()throws Exception {context=InstrumentationRegistry.getInstrumentation().getTargetContext();cache=new File(context.getCacheDir(),"ai-image-test-"+UUID.randomUUID()).getCanonicalFile();assertTrue(cache.mkdir());images=new AiTemporaryImages(cache,System::currentTimeMillis,AiImageCodec::process);operation=UUID.randomUUID();images.create(operation);}
    @After public void cleanup()throws Exception {images.discard(operation);File root=new File(cache,"ai-import");assertTrue(root.delete());assertTrue(cache.delete());}
    private byte[] bitmap(Bitmap.CompressFormat format)throws Exception {Bitmap source=Bitmap.createBitmap(200,100,Bitmap.Config.ARGB_8888);try(ByteArrayOutputStream out=new ByteArrayOutputStream()){Canvas canvas=new Canvas(source);Paint paint=new Paint();paint.setColor(Color.RED);canvas.drawRect(0,0,80,100,paint);assertTrue(source.compress(format,100,out));return out.toByteArray();}finally{source.recycle();}}
    private byte[] oriented(int value)throws Exception {File file=new File(cache,"generated-exif.jpg");try{try(OutputStream out=new FileOutputStream(file)){out.write(bitmap(Bitmap.CompressFormat.JPEG));}ExifInterface exif=new ExifInterface(file.getAbsolutePath());exif.setAttribute(ExifInterface.TAG_ORIENTATION,Integer.toString(value));exif.saveAttributes();return AiTemporaryImages.read(file,1000000);}finally{assertTrue(file.delete());}}
    @Test public void transparentPngBecomesWhiteJpegWithoutPersistingSource()throws Exception {AiTemporaryImages.Image result=images.importStream(operation,new ByteArrayInputStream(bitmap(Bitmap.CompressFormat.PNG)),"image/png");File jpeg=new File(new File(cache,"ai-import/"+operation),result.id+".jpg");Bitmap decoded=BitmapFactory.decodeFile(jpeg.getAbsolutePath());try{int pixel=decoded.getPixel(190,50);assertTrue(Color.red(pixel)>240&&Color.green(pixel)>240&&Color.blue(pixel)>240);}finally{decoded.recycle();}assertEquals(2,Objects.requireNonNull(jpeg.getParentFile().list()).length);}
    @Test public void exifRotateFlipAndTransposeUseRealSampleGeometry()throws Exception {for(int orientation:new int[]{2,3,4,5,6,7,8}){AiTemporaryImages.Image image=images.importStream(operation,new ByteArrayInputStream(oriented(orientation)),"image/jpeg");assertEquals(orientation>=5?100:200,image.width);assertEquals(orientation>=5?200:100,image.height);Bitmap decoded=BitmapFactory.decodeFile(new File(cache,"ai-import/"+operation+"/"+image.id+".jpg").getAbsolutePath());try{int x=orientation==2||orientation==3?image.width-20:20;int y=orientation==7||orientation==8?image.height-20:20;assertTrue("orientation "+orientation,Color.red(decoded.getPixel(x,y))>200&&Color.green(decoded.getPixel(x,y))<80);}finally{decoded.recycle();}images.remove(operation,UUID.fromString(image.id));}}
    @Test public void boundsAndDownsampleUseRealLargeBitmap()throws Exception {Bitmap source=Bitmap.createBitmap(4000,4000,Bitmap.Config.ARGB_8888);byte[] bytes;try(ByteArrayOutputStream out=new ByteArrayOutputStream()){assertTrue(source.compress(Bitmap.CompressFormat.PNG,100,out));bytes=out.toByteArray();}finally{source.recycle();}AiTemporaryImages.Image image=images.importStream(operation,new ByteArrayInputStream(bytes),"image/png");assertTrue(image.width<=2048&&image.height<=2048);assertTrue(image.byteSize<=1024*1024);}
    @Test public void falseMimeBadUriAndOwnFileProviderAreRejected()throws Exception {assertThrows(AiFailure.class,()->images.importStream(operation,new ByteArrayInputStream(bitmap(Bitmap.CompressFormat.PNG)),"image/jpeg"));for(Uri uri:new Uri[]{Uri.parse("file:///data/private.jpg"),Uri.parse("content://"+context.getPackageName()+".fileprovider/images/a.jpg"),Uri.parse("content://unresolvable.test/missing")})assertThrows(AiFailure.class,()->images.importSelectedUri(context,operation,uri));}
    @Test public void symlinkToOtherFolderIsNeverFollowedAndBlocksCleanupSafely()throws Exception {File outside=new File(cache,"outside");assertTrue(outside.mkdir());File link=new File(cache,"ai-import/"+operation+"/"+UUID.randomUUID()+".jpg");Os.symlink(outside.getAbsolutePath(),link.getAbsolutePath());try{assertTrue(images.cleanupAbandoned());assertThrows(AiFailure.class,()->images.discard(operation));assertTrue(outside.isDirectory());assertTrue(link.exists());}finally{assertTrue(link.delete());assertTrue(outside.delete());}}
    @Test public void rootSymlinkIsRejectedWithoutTouchingTarget()throws Exception {File fresh=new File(cache,"fresh"),outside=new File(cache,"outside");assertTrue(fresh.mkdir());assertTrue(outside.mkdir());File link=new File(fresh,"ai-import");Os.symlink(outside.getAbsolutePath(),link.getAbsolutePath());try{assertThrows(AiFailure.class,()->new AiTemporaryImages(fresh,System::currentTimeMillis,AiImageCodec::process));assertEquals(0,Objects.requireNonNull(outside.list()).length);}finally{assertTrue(link.delete());assertTrue(fresh.delete());assertTrue(outside.delete());}}
}
