package app.recipio.local;
import static org.junit.Assert.*;
import java.io.*;
import java.nio.file.Files;
import java.util.*;
import java.util.concurrent.atomic.AtomicBoolean;
import org.junit.*;

public class AiTemporaryImagesTest {
    private File cache;private long[] now;private AiTemporaryImages images;private UUID a,b;
    private final byte[] jpeg={(byte)255,(byte)216,(byte)255,(byte)217};
    @Before public void before()throws Exception {cache=Files.createTempDirectory("recipio-ai-fixture-").toFile();now=new long[]{100};images=new AiTemporaryImages(cache,()->now[0],(file,mime)->new AiTemporaryImages.Processed(jpeg,200,100));a=UUID.randomUUID();b=UUID.randomUUID();images.create(a);images.create(b);}
    @After public void after()throws Exception {try(java.util.stream.Stream<java.nio.file.Path> paths=Files.walk(cache.toPath())){for(java.nio.file.Path p:paths.sorted(Comparator.reverseOrder()).toArray(java.nio.file.Path[]::new))Files.deleteIfExists(p);}}
    private AiTemporaryImages.Image add(UUID op)throws Exception {return images.importStream(op,new ByteArrayInputStream(jpeg),"image/jpeg");}
    private File folder(UUID op){return new File(cache,"ai-import/"+op);}
    @Test public void usesGeneratedHandlesPrivateCacheAndCleansOriginal()throws Exception {AiTemporaryImages.Image image=add(a);assertTrue(image.previewUri.endsWith("/ai-import/"+a+"/"+image.id+".jpg"));assertEquals(4,image.byteSize);assertEquals(2,Objects.requireNonNull(folder(a).list()).length);assertFalse(new File(cache,"images").exists());}
    @Test public void actualOriginalByteBoundaryAndClosedStream()throws Exception {AtomicBoolean closed=new AtomicBoolean();InputStream tooLarge=new ByteArrayInputStream(new byte[15*1024*1024+1]){@Override public void close(){closed.set(true);}};assertEquals("image_too_large",assertThrows(AiFailure.class,()->images.importStream(a,tooLarge,"image/jpeg")).code);assertTrue(closed.get());assertEquals(1,Objects.requireNonNull(folder(a).list()).length);}
    @Test public void emptyAndUnapprovedMimeNeverReachProcessor() {assertEquals("image_invalid",assertThrows(AiFailure.class,()->images.importStream(a,new ByteArrayInputStream(new byte[0]),"image/jpeg")).code);assertEquals("image_invalid",assertThrows(AiFailure.class,()->images.importStream(a,new ByteArrayInputStream(jpeg),"image/avif")).code);}
    @Test public void sixImagesAllowedSeventhRejectedAndRequestOrderingPreserved()throws Exception {List<UUID> ids=new ArrayList<>();for(int i=0;i<6;i++)ids.add(UUID.fromString(add(a).id));assertEquals("image_too_large",assertThrows(AiFailure.class,()->add(a)).code);assertEquals(6,(int)images.withPinnedImages(a,ids,List::size));assertEquals("image_invalid",assertThrows(AiFailure.class,()->images.withPinnedImages(a,Arrays.asList(ids.get(0),ids.get(0)),List::size)).code);}
    @Test public void handlesCannotCrossSessionsAndRemovingOneDoesNotRemoveOther()throws Exception {AiTemporaryImages.Image first=add(a),second=add(a),foreign=add(b);assertThrows(AiFailure.class,()->images.remove(b,UUID.fromString(first.id)));assertThrows(AiFailure.class,()->images.withPinnedImages(a,Collections.singletonList(UUID.fromString(foreign.id)),List::size));images.remove(a,UUID.fromString(first.id));assertTrue(new File(folder(a),second.id+".jpg").isFile());assertTrue(new File(folder(b),foreign.id+".jpg").isFile());}
    @Test public void failedRequestRetainsImageButDiscardWaitsForPinnedRead()throws Exception {UUID id=UUID.fromString(add(a).id);assertThrows(IOException.class,()->images.withPinnedImages(a,Collections.singletonList(id),list->{throw new IOException("fake request");}));assertTrue(new File(folder(a),id+".jpg").exists());images.withPinnedImages(a,Collections.singletonList(id),list->{images.discard(a);assertTrue(new File(folder(a),id+".jpg").exists());return null;});assertFalse(folder(a).exists());assertTrue(folder(b).exists());}
    @Test public void lateSelectionAfterDiscardIsRemovedWithoutRegistering()throws Exception {AiTemporaryImages[] own=new AiTemporaryImages[1];UUID target=UUID.randomUUID();own[0]=new AiTemporaryImages(cache,()->now[0],(file,mime)->{own[0].discard(target);return new AiTemporaryImages.Processed(jpeg,200,100);});own[0].create(target);assertEquals("stale_session",assertThrows(AiFailure.class,()->own[0].importStream(target,new ByteArrayInputStream(jpeg),"image/jpeg")).code);assertFalse(folder(target).exists());}
    @Test public void outputLimitsRejectLargeOrThinImagesWithoutRetainingFiles()throws Exception {AiTemporaryImages bad=new AiTemporaryImages(cache,()->now[0],(f,m)->new AiTemporaryImages.Processed(new byte[1024*1024+1],200,100));UUID op=UUID.randomUUID();bad.create(op);assertEquals("image_too_large",assertThrows(AiFailure.class,()->bad.importStream(op,new ByteArrayInputStream(jpeg),"image/jpeg")).code);assertEquals(1,Objects.requireNonNull(folder(op).list()).length);}
    @Test public void startupCleansOnlyRegisteredCrashRemnantsNotImagesOrUnknownFolders()throws Exception {add(a);File unrelated=new File(cache,"images");assertTrue(unrelated.mkdir());File unregistered=new File(cache,"ai-import/"+UUID.randomUUID());assertTrue(unregistered.mkdir());assertFalse(new AiTemporaryImages(cache,()->now[0],(f,m)->null).cleanupAbandoned());assertFalse(folder(a).exists());assertFalse(folder(b).exists());assertTrue(unrelated.exists());assertTrue(unregistered.exists());}
    @Test public void activeStaleSessionExpiresAt24HoursButClockRollbackDoesNotExpireActiveSession()throws Exception {add(a);now[0]=0;images.cleanupAbandoned();assertTrue(folder(a).exists());now[0]=100+24L*60*60*1000-1;images.cleanupAbandoned();assertTrue(folder(a).exists());now[0]++;images.cleanupAbandoned();assertFalse(folder(a).exists());}
    @Test public void unexpectedFilesAreNotDeleted()throws Exception {File unexpected=new File(folder(a),"unregistered.txt");assertTrue(unexpected.createNewFile());assertTrue(images.cleanupAbandoned());assertThrows(AiFailure.class,()->images.discard(a));assertTrue(unexpected.exists());}
    @Test public void dimensionsAndSampleBudgetAreExact()throws Exception {AiImageCodec.dimensions(8000,4000);assertEquals("image_too_large",assertThrows(AiFailure.class,()->AiImageCodec.dimensions(8001,4000)).code);assertThrows(AiFailure.class,()->AiImageCodec.dimensions(10000,11));assertThrows(AiFailure.class,()->AiImageCodec.dimensions(10,100));assertEquals(4,AiImageCodec.sampleSize(8000,4000));assertEquals(2,AiImageCodec.sampleSize(4000,4000));}
    @Test public void rejectingSeventhImageMustNotDecrementAnUnacquiredPin()throws Exception {for(int i=0;i<6;i++)add(a);assertThrows(AiFailure.class,()->add(a));images.discard(a);assertFalse(folder(a).exists());}
    @Test public void fullOriginalLimitIsAllowedAndOutputFailureDoesNotRetainOriginal()throws Exception {byte[] bytes=new byte[15*1024*1024];AiTemporaryImages.Image accepted=images.importStream(a,new ByteArrayInputStream(bytes),"image/jpeg");assertEquals(4,accepted.byteSize);AiTemporaryImages failing=new AiTemporaryImages(cache,()->now[0],(f,m)->{throw new IOException();});UUID id=UUID.randomUUID();failing.create(id);assertThrows(AiFailure.class,()->failing.importStream(id,new ByteArrayInputStream(jpeg),"image/jpeg"));assertEquals(1,Objects.requireNonNull(folder(id).list()).length);}
    @Test public void boundsAt16MPAndOversizedWideInputs()throws Exception {AiImageCodec.dimensions(4000,4000);AiImageCodec.dimensions(8000,4000);assertThrows(AiFailure.class,()->AiImageCodec.dimensions(Integer.MAX_VALUE,Integer.MAX_VALUE));}
}
