import "fake-indexeddb/auto";
import {afterEach,beforeEach,expect,it,vi} from "vitest";
import {fireEvent,render,screen,waitFor} from "@testing-library/react";
import {LibraryApp} from "../library-app";
import {PreviewRecipeLibrary} from "../preview-store";
import {AiIntakeService} from "./service";
import {fakeAi} from "./service.test-support";
import {__resetLocalDatabaseForTests} from "@/features/offline/local-db";
afterEach(__resetLocalDatabaseForTests);
beforeEach(()=>vi.spyOn(window,"scrollTo").mockImplementation(()=>{}));
it("actual App preview shares acknowledgement and hardware Back preserves dirty edits when declined",async()=>{const fake=fakeAi(),store=new PreviewRecipeLibrary(),service=new AiIntakeService(fake.keys,fake.bridge,{store}),create=vi.spyOn(store,"createDetails");render(<LibraryApp store={store} ai={service}/>);fireEvent.click(await screen.findByRole("button",{name:"新增菜谱"}));fireEvent.click(await screen.findByRole("button",{name:"AI 整理"}));fireEvent.change(await screen.findByLabelText("菜谱文字"),{target:{value:"啤酒鸭"}});await waitFor(()=>expect(screen.getByRole("button",{name:"开始 AI 整理"})).toBeEnabled());fireEvent.click(screen.getByRole("button",{name:"开始 AI 整理"}));await screen.findByRole("heading",{name:"检查 AI 整理结果"});fireEvent.click(screen.getByRole("button",{name:"快速保存菜谱"}));expect(create).not.toHaveBeenCalled();expect(screen.getByRole("region",{name:"AI 整理审核"})).toHaveFocus();fireEvent.click(screen.getByRole("checkbox",{name:"我已检查推断或缺失内容"}));expect(service.snapshot().confirmed).toBe(true);fireEvent.change(screen.getByLabelText("菜名"),{target:{value:"自己的鸭"}});const confirm=vi.spyOn(window,"confirm").mockReturnValue(false);fireEvent(window,new Event("recipio:back",{cancelable:true}));expect(screen.getByLabelText("菜名")).toHaveValue("自己的鸭");expect(confirm).toHaveBeenCalled();confirm.mockRestore();});
async function openPreview(store:PreviewRecipeLibrary,service:AiIntakeService){render(<LibraryApp store={store} ai={service}/>);fireEvent.click(await screen.findByRole("button",{name:"新增菜谱"}));fireEvent.click(await screen.findByRole("button",{name:"AI 整理"}));fireEvent.change(await screen.findByLabelText("菜谱文字"),{target:{value:"鸭"}});await waitFor(()=>expect(screen.getByRole("button",{name:"开始 AI 整理"})).toBeEnabled());fireEvent.click(screen.getByRole("button",{name:"开始 AI 整理"}));await screen.findByRole("heading",{name:"检查 AI 整理结果"});fireEvent.click(screen.getByRole("checkbox",{name:"我已检查推断或缺失内容"}));}
it("App warns about exact duplicate beyond page 100; cancel writes nothing and explicit continue creates another recipe",async()=>{
  const fake=fakeAi(),store=new PreviewRecipeLibrary(),service=new AiIntakeService(fake.keys,fake.bridge,{store});await store.create("啤酒鸭");for(let i=0;i<101;i++)await store.create(`另一道${i}`);await openPreview(store,service);const create=vi.spyOn(store,"createDetails");fireEvent.click(screen.getByRole("button",{name:"快速保存菜谱"}));await screen.findByRole("dialog",{name:"已存在同名菜谱"});fireEvent.click(screen.getByRole("button",{name:"返回检查"}));expect(create).not.toHaveBeenCalled();expect(screen.getByLabelText("菜名")).toHaveValue("啤酒鸭");await waitFor(()=>expect(screen.getByRole("button",{name:"快速保存菜谱"})).toBeEnabled());fireEvent.click(screen.getByRole("button",{name:"快速保存菜谱"}));fireEvent.click(await screen.findByRole("button",{name:"仍然新建菜谱"}));await screen.findByRole("heading",{name:"啤酒鸭"});expect(create).toHaveBeenCalledTimes(1);expect(await store.list("啤酒鸭")).toHaveLength(2);
});
it("failed same-name read blocks create and preserves edits with local error",async()=>{
  const fake=fakeAi(),store=new PreviewRecipeLibrary(),service=new AiIntakeService(fake.keys,fake.bridge,{store});await openPreview(store,service);vi.spyOn(store,"hasExactTitle").mockRejectedValueOnce(new Error("private diagnostics"));const create=vi.spyOn(store,"createDetails");fireEvent.click(screen.getByRole("button",{name:"快速保存菜谱"}));await screen.findByText("同名检查未完成，请重试；当前内容尚未保存。");expect(create).not.toHaveBeenCalled();expect(screen.queryByText("private diagnostics")).not.toBeInTheDocument();expect(screen.getByLabelText("菜名")).toHaveValue("啤酒鸭");
});
it("unknown commit UI has only explicit read recovery and Back cannot discard the attempt",async()=>{
  const fake=fakeAi(),store=new PreviewRecipeLibrary(),service=new AiIntakeService(fake.keys,fake.bridge,{store});await openPreview(store,service);const original=store.createDetails.bind(store),create=vi.spyOn(store,"createDetails").mockImplementationOnce(async(...args)=>{await original(...args);throw new Error("lost");});vi.spyOn(store,"getDetails").mockRejectedValueOnce(new Error("read failed"));fireEvent.click(screen.getByRole("button",{name:"快速保存菜谱"}));await screen.findByRole("heading",{name:"先核对保存结果"});expect(screen.queryByLabelText("菜名")).not.toBeInTheDocument();fireEvent(window,new Event("recipio:back",{cancelable:true}));expect(service.snapshot().phase).toBe("uncertain");fireEvent.click(screen.getByRole("button",{name:"核对保存结果"}));await screen.findByRole("heading",{name:"啤酒鸭"});expect(create).toHaveBeenCalledTimes(1);
});
